### ISSUE TITLE
bug with MiniaturePets

### ISSUE THREAD

**Issue by games4681** [GC-spigot/AdvancedTrades#16]
### Describe the bug

Could not pass event PlayerQuitEvent to MiniaturePets v2.7.7

java.lang.NullPointerException: Cannot invoke "com.kirelcodes.miniaturepets.pets.Pet.remove(boolean, boolean)" because the return value of "com.kirelcodes.miniaturepets.pets.PetManager.getPet(org.bukkit.entity.Player)" is null

at com.kirelcodes.miniaturepets.listeners.PlayerQuitListener.playerLeaveEvent(PlayerQuitListener.java:35) ~[MiniaturePets-3.0.1.jar:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor887.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]

at net.minecraft.server.players.PlayerList.remove(PlayerList.java:578) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.players.PlayerList.remove(PlayerList.java:563) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2119) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2098) ~[?:?]

at net.minecraft.network.Connection.handleDisconnection(Connection.java:777) ~[?:?]

at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]

at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

In the console every time when a player exits the error appears. It is not clear why

**Comment by games4681** [comment]
i closed bad support team
