### ISSUE TITLE
[15:34:22 ERROR]: Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.7

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedTrades#9]
### Describe the bug

[15:34:22 ERROR]: Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.7
java.lang.IllegalStateException: null
        at java.util.ArrayList$Itr.remove(ArrayList.java:980) ~[?:?]
        at net.advancedplugins.at.handlers.TradeBuilder.build(TradeBuilder.java:72) ~[AdvancedTrades-1.0.7.jar:?]
        at net.advancedplugins.at.listeners.VillagerTradesPopulator.onVillagerAcquireTradeEvent(VillagerTradesPopulator.java:37) ~[AdvancedTrades-1.0.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor192.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1487]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:289) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:1006) ~[?:?]
        at net.minecraft.world.entity.npc.AbstractVillager.getOffers(AbstractVillager.java:130) ~[?:?]
        at net.minecraft.world.entity.npc.AbstractVillager.addAdditionalSaveData(AbstractVillager.java:198) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.addAdditionalSaveData(Villager.java:566) ~[?:?]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2111) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2000) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.world.entity.Entity.save(Entity.java:2016) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$storeEntities$1(EntityStorage.java:107) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.chunk.storage.EntityStorage.storeEntities(EntityStorage.java:94) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:327) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:301) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.server.level.ChunkMap.saveIncrementally(ChunkMap.java:865) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.server.level.ServerChunkCache.saveIncrementally(ServerChunkCache.java:881) ~[?:?]
        at net.minecraft.server.level.ServerLevel.saveIncrementally(ServerLevel.java:1285) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1487]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Not sure how this is produced

**Comment by GC-spigot** [comment]
Will be fixed in next update
